#!/usr/bin/env bash

set -euo pipefail

## Setup variables from the plugin properties
PLATFORM="${BUILDKITE_PLUGIN_UM_IOS_BUILDER_PLATFORM:-undefined}"
PODSPEC_FILE="${BUILDKITE_PLUGIN_UM_IOS_BUILDER_FILE_PATH:-undefined}"

## Setup variables from the environment
SKIP=$(buildkite-agent meta-data get 'skip-test' --default 'true')

function validate_contract_podspec() {
  local podspec_file=$1

  echo "--- :hammer: Validating Contract"

  # Below code stolen from https://github.com/actions/runner-images/blob/5a6e2158591c3f3b0c732691694d061fea8f792e/images/macos/scripts/build/configure-xcode.sh

  # quit the CoreSimulatorService
  launchctl remove com.apple.CoreSimulator.CoreSimulatorService || true
  # add sleep to let CoreSimulatorService to exit
  sleep 3
  # erase the devices
  xcrun simctl erase all
  # add sleep due to sometimes "xcrun simctl list" takes more than a few moments and script fails when trying to remove CoreSimulatorSerivce
  sleep 10

  BASEDIR=$(pwd)

  cd ios/contract/example
  bundle install --quiet
  bundle exec pod update
  cd "$BASEDIR"
  bundle exec pod lib lint $podspec_file --sources='git@github.com:fanduel/private-podspecs.git,https://cdn.cocoapods.org' --private --verbose --allow-warnings
}

function build_library_and_validate_podspec() {
  local podspec_file=$1

  echo "--- :hammer: Building Library"

  BASEDIR=$(pwd)

  cd ios/library
  rbenv install --skip-existing

  cd test-harness
  bundle install --quiet
  bundle exec pod update

  # Build the library test harness
  bundle exec fastlane buildLibrary

  # Validate library podspec
  echo "--- :hammer: Validating Podspec"
  cd $BASEDIR
  rm Gemfile.lock
  bundle install --quiet
  bundle exec pod lib lint $podspec_file --sources='git@github.com:fanduel/private-podspecs.git,https://cdn.cocoapods.org' --private --verbose --allow-warnings
}

function build_react_native_library() {
  echo "--- :hammer: Building RN iOS Library"

  BASEDIR=$(pwd)

  ## Copy .npmrc files to the correct locations
  cp .npmrc react/library/
  cp .npmrc react/library/test-harness/

  cd react/library/
  npm ci

  cd test-harness
  rbenv install --skip-existing
  bundle install --quiet
  npm ci

  cd ios
  bundle exec pod install
  bundle exec fastlane buildLibrary

  cd "$BASEDIR"
}

## Check skip-test is true, we don't build the contract or library
if [[ "$SKIP" == "true" ]]; then
  echo "--- :double_vertical_bar: Skipping test as skip-test was set to true"
  exit 0
fi

# Check if the platform is set to contract or library and perform steps accordingly
if [[ "$PLATFORM" == "ios-contract" ]]; then
  validate_contract_podspec $PODSPEC_FILE
elif [[ "$PLATFORM" == "ios-library" ]]; then
  build_library_and_validate_podspec $PODSPEC_FILE
elif [[ "$PLATFORM" == "react-library" ]]; then
  build_react_native_library
else
  echo "--- :warning: Platform needs to be one of these: [ios-contract, ios-library, react-library]"
  exit 0
fi
